app = 'library-client'
primary_region = 'cdg'

[build]

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[statics]]
guest_path = "/usr/share/nginx/html"
url_prefix = "/"
fallback = "index.html"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
