name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@v1
        with:
          args: "deploy -c server/LibraryProject.Api/fly.toml"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
