name: Docker Build & Push

on:
  push:
    branches: [ main, develop ]
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Api/LibraryProject.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/library-project/library-api:sha-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/library-project/library-api:${{ github.ref_name == 'main' && 'latest' || 'edge' }}
      
      
      - name: Tag release image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull ghcr.io/${{ github.repository }}/library-api:latest
          docker tag ghcr.io/${{ github.repository }}/library-api:latest ghcr.io/${{ github.repository }}/library-api:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/${{ github.repository }}/library-api:${GITHUB_REF#refs/tags/}
